app:
  port: :8080
  mode: debug
  domain_prefix: cardshop.local

db:
  host: localhost
  port: 3306
  user: root
  password: Aa123789@
  name: card_system
  ssl_mode: disable

jwt:
  secret_key: your-secret-key
  expire_hours: 24
  refresh_expire: 168

redis:
  host: localhost
  port: 6379
  password:
  db: 0